services:
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Operators\OperatorSpacingSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Traits\UseDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Classes\ClosingBraceSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Classes\AnonClassDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Classes\ClassInstantiationSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Namespaces\CompoundNamespaceDepthSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Properties\ConstantVisibilitySniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Files\ImportStatementSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Files\FileHeaderSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Files\OpenTagSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Files\DeclareStatementSniff: ~
#  报错
#  PHP_CodeSniffer\Standards\PSR12\Sniffs\Functions\NullableTypeDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Functions\ReturnTypeDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\ControlStructures\ControlStructureSpacingSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\ControlStructures\BooleanOperatorPlacementSniff: ~
  PHP_CodeSniffer\Standards\PSR12\Sniffs\Keywords\ShortFormTypeKeywordsSniff: ~
  PHP_CodeSniffer\Standards\PSR1\Sniffs\Methods\CamelCapsMethodNameSniff: ~
  PHP_CodeSniffer\Standards\PSR1\Sniffs\Classes\ClassDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR1\Sniffs\Files\SideEffectsSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DisallowAlternativePHPTagsSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DisallowShortOpenTagSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Files\ByteOrderMarkSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Classes\ValidClassNameSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\NamingConventions\UpperCaseConstantNameSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineEndingsSniff:
    eolChar: '\n'
  PHP_CodeSniffer\Standards\PSR2\Sniffs\Files\EndFileNewlineSniff: ~
  PHP_CodeSniffer\Standards\PSR2\Sniffs\Files\ClosingTagSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineLengthSniff:
    lineLimit: 120
    absoluteLineLimit: 0
  PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\SuperfluousWhitespaceSniff:
    ignoreBlankLines: true
  PHP_CodeSniffer\Standards\Generic\Sniffs\Formatting\DisallowMultipleStatementsSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\ScopeIndentSniff:
    ignoreIndentationTokens:
      - T_COMMENT
      - T_DOC_COMMENT_OPEN_TAG
  PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\DisallowTabIndentSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\LowerCaseKeywordSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\LowerCaseConstantSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\LowerCaseTypeSniff: ~
  PHP_CodeSniffer\Standards\PSR2\Sniffs\Classes\ClassDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR2\Sniffs\Classes\PropertyDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Scope\MethodScopeSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\ScopeKeywordSpacingSniff: ~
  PHP_CodeSniffer\Standards\PSR2\Sniffs\Methods\MethodDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR2\Sniffs\Methods\FunctionClosingBraceSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Functions\FunctionDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Functions\LowercaseFunctionKeywordsSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Functions\FunctionDeclarationArgumentSpacingSniff:
    equalsSpacing: 1
  PHP_CodeSniffer\Standards\PEAR\Sniffs\Functions\ValidDefaultValueSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Functions\MultiLineFunctionDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Functions\FunctionCallArgumentSpacingSniff: ~
  PHP_CodeSniffer\Standards\PSR2\Sniffs\Methods\FunctionCallSignatureSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ControlSignatureSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\ControlStructureSpacingSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\ScopeClosingBraceSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForEachLoopDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForLoopDeclarationSniff:
    ignoreNewlines: true
  PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\LowercaseDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\ControlStructures\InlineControlStructureSniff:
    error: true
  PHP_CodeSniffer\Standards\PSR2\Sniffs\ControlStructures\ElseIfDeclarationSniff: ~
  PHP_CodeSniffer\Standards\PSR2\Sniffs\ControlStructures\SwitchDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\IncrementDecrementSpacingSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\CastSpacingSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayBracketSpacingSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\DocCommentAlignmentSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\EmptyCatchCommentSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\LongConditionClosingCommentSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\Commenting\PostStatementCommentSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Commenting\TodoSniff: ~
  PHP_CodeSniffer\Standards\Zend\Sniffs\Files\ClosingTagSniff: ~
  PHP_CodeSniffer\Standards\PEAR\Sniffs\Functions\FunctionCallSignatureSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Arrays\DisallowLongArraySyntaxSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Formatting\SpaceAfterCastSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Formatting\SpaceAfterNotSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\BacktickOperatorSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\CharacterBeforePHPOpeningTagSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\ForbiddenFunctionsSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\SAPIUsageSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\SyntaxSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\VersionControl\GitMergeConflictSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\ArbitraryParenthesesSpacingSniff: ~
  PHP_CodeSniffer\Standards\PEAR\Sniffs\WhiteSpace\ObjectOperatorIndentSniff: ~
  PHP_CodeSniffer\Standards\PEAR\Sniffs\WhiteSpace\ScopeClosingBraceSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\LanguageConstructSpacingSniff: ~
  SlevomatCodingStandard\Sniffs\Arrays\TrailingArrayCommaSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\NamespaceSpacingSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\RequireOneNamespaceInFileSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\FullyQualifiedClassNameInAnnotationSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff:
    searchAnnotations: true
  SlevomatCodingStandard\Sniffs\Namespaces\UseDoesNotStartWithBackslashSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\UseSpacingSniff: ~
  SlevomatCodingStandard\Sniffs\Operators\SpreadOperatorSpacingSniff: ~
  SlevomatCodingStandard\Sniffs\PHP\ShortListSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSpacingSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSpacingSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\UnnecessaryFinalModifierSniff: ~
  SlevomatCodingStandard\Sniffs\Classes\ClassConstantVisibilitySniff: ~
  SlevomatCodingStandard\Sniffs\Classes\DisallowLateStaticBindingForConstantsSniff: ~
  SlevomatCodingStandard\Sniffs\Classes\ModernClassNameReferenceSniff: ~
  SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff: ~
  SlevomatCodingStandard\Sniffs\Classes\UselessLateStaticBindingSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Arrays\ArrayIndentSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\EmptyPHPStatementSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\EmptyStatementSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\ForLoopShouldBeWhileLoopSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\ForLoopWithTestFunctionCallSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\JumbledIncrementerSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\UnconditionalIfStatementSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\UselessOverridingMethodSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DiscourageGotoSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\NoSilencedErrorsSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Strings\UnnecessaryStringConcatSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\PHP\EvalSniff: ~
  PHP_CodeSniffer\Standards\Zend\Sniffs\Debug\CodeAnalyzerSniff: ~
  SlevomatCodingStandard\Sniffs\Arrays\DisallowImplicitArrayCreationSniff: ~
  SlevomatCodingStandard\Sniffs\ControlStructures\AssignmentInConditionSniff: ~
  SlevomatCodingStandard\Sniffs\ControlStructures\DisallowContinueWithoutIntegerOperandInSwitchSniff: ~
  SlevomatCodingStandard\Sniffs\ControlStructures\DisallowYodaComparisonSniff: ~
  SlevomatCodingStandard\Sniffs\ControlStructures\LanguageConstructWithParenthesesSniff: ~
  SlevomatCodingStandard\Sniffs\Exceptions\DeadCatchSniff: ~
  SlevomatCodingStandard\Sniffs\Functions\UnusedInheritedVariablePassedToClosureSniff: ~
  SlevomatCodingStandard\Sniffs\Functions\UselessParameterDefaultValueSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\UseFromSameNamespaceSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\UselessAliasSniff: ~
  SlevomatCodingStandard\Sniffs\Operators\RequireCombinedAssignmentOperatorSniff: ~
  SlevomatCodingStandard\Sniffs\Operators\RequireOnlyStandaloneIncrementAndDecrementOperatorsSniff: ~
  SlevomatCodingStandard\Sniffs\PHP\OptimizedFunctionsWithoutUnpackingSniff: ~
  SlevomatCodingStandard\Sniffs\PHP\TypeCastSniff: ~
  SlevomatCodingStandard\Sniffs\PHP\UselessParenthesesSniff: ~
  SlevomatCodingStandard\Sniffs\PHP\UselessSemicolonSniff: ~
  SlevomatCodingStandard\Sniffs\Variables\DuplicateAssignmentToVariableSniff: ~
  SlevomatCodingStandard\Sniffs\Variables\UselessVariableSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Commenting\FixmeSniff: ~
  SlevomatCodingStandard\Sniffs\Commenting\EmptyCommentSniff: ~
  SlevomatCodingStandard\Sniffs\Commenting\ForbiddenCommentsSniff: ~
  SlevomatCodingStandard\Sniffs\Commenting\InlineDocCommentDeclarationSniff: ~
  SlevomatCodingStandard\Sniffs\Commenting\UselessFunctionDocCommentSniff: ~
  SlevomatCodingStandard\Sniffs\Commenting\UselessInheritDocCommentSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\LongTypeHintsSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\NullableTypeForNullDefaultValueSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\NullTypeHintOnLastPositionSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff: ~
  SlevomatCodingStandard\Sniffs\TypeHints\UselessConstantTypeHintSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\UnusedFunctionParameterSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Functions\CallTimePassByReferenceSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DeprecatedFunctionsSniff: ~
  PHP_CodeSniffer\Standards\Squiz\Sniffs\PHP\GlobalKeywordSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Files\OneClassPerFileSniff: ~
  SlevomatCodingStandard\Sniffs\Classes\SuperfluousAbstractClassNamingSniff: ~
  SlevomatCodingStandard\Sniffs\Classes\SuperfluousInterfaceNamingSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Files\OneInterfacePerFileSniff: ~
  SlevomatCodingStandard\Sniffs\Namespaces\NamespaceDeclarationSniff: ~
  PHP_CodeSniffer\Standards\Generic\Sniffs\Files\OneTraitPerFileSniff: ~
  SlevomatCodingStandard\Sniffs\Classes\SuperfluousTraitNamingSniff: ~

parameters:
  skip:
    PHP_CodeSniffer\Standards\PSR12\Sniffs\Files\FileHeaderSniff.SpacingAfterBlock: ~
    PHP_CodeSniffer\Standards\PSR12\Sniffs\Files\FileHeaderSniff.IncorrectOrder: ~
    PHP_CodeSniffer\Standards\PSR12\Sniffs\Files\FileHeaderSniff.IncorrectGrouping: ~
    SlevomatCodingStandard\Sniffs\Commenting\InlineDocCommentDeclarationSniff.MissingVariable: ~
    SlevomatCodingStandard\Sniffs\Commenting\InlineDocCommentDeclarationSniff.NoAssignment: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff.MissingTraversableTypeHintSpecification: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff.MissingAnyTypeHint: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff.MissingNativeTypeHint: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff.UselessAnnotation: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff.MissingTraversableTypeHintSpecification: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff.MissingAnyTypeHint: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff.MissingNativeTypeHint: ~
    SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff.UselessAnnotation: ~
    SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff.MissingTraversableTypeHintSpecification: ~
    SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff.MissingAnyTypeHint: ~
    SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff.MissingNativeTypeHint: ~
    SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff.UselessAnnotation: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.DoubleArrowNotAligned: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.NoKeySpecified: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.KeySpecified: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.SingleLineNotAllowed: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.KeyNotAligned: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.ValueNotAligned: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.CloseBraceNotAligned: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.CloseBraceNewLine: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\Arrays\ArrayDeclarationSniff.MultiLineNotAllowed: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\SuperfluousWhitespaceSniff.StartFile: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\SuperfluousWhitespaceSniff.EndFile: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\SuperfluousWhitespaceSniff.EmptyLines: ~
    PHP_CodeSniffer\Standards\PSR2\Sniffs\Methods\FunctionCallSignatureSniff.SpaceAfterCloseBracket: ~
    PHP_CodeSniffer\Standards\PSR2\Sniffs\Methods\FunctionCallSignatureSniff.OpeningIndent: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForLoopDeclarationSniff.SpacingAfterOpen: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForLoopDeclarationSniff.SpacingBeforeClose: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForEachLoopDeclarationSniff.AsNotLower: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForEachLoopDeclarationSniff.SpaceAfterOpen: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForEachLoopDeclarationSniff.SpaceBeforeClose: ~
    PHP_CodeSniffer\Standards\PEAR\Sniffs\Functions\FunctionCallSignatureSniff.Indent: ~
    SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff.UnusedMethod: ~
    SlevomatCodingStandard\Sniffs\Commenting\UselessFunctionDocCommentSniff.UselessDocComment: ~
    PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\ControlStructureSpacingSniff.LineAfterClose: ~